services:
  db:
    container_name: "social0-db"
    image: postgres:12.4-alpine
    volumes:
      - "./database/postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "social0-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped