// @ts-nocheck
import * as __fd_glob_68 from "../content/docs/dashboard/connections/linkedin/select.md?collection=docs"
import * as __fd_glob_67 from "../content/docs/dashboard/connections/instagram/select.md?collection=docs"
import * as __fd_glob_66 from "../content/docs/dashboard/posts/[id]/edit.md?collection=docs"
import * as __fd_glob_65 from "../content/docs/dashboard/connections/facebook/select.md?collection=docs"
import * as __fd_glob_64 from "../content/docs/dashboard/connect/instagram-facebook/select.md?collection=docs"
import * as __fd_glob_63 from "../content/docs/developer/pages/posts.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/developer/pages/index.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/dashboard/posts/scheduled.md?collection=docs"
import * as __fd_glob_60 from "../content/docs/dashboard/posts/posted.md?collection=docs"
import * as __fd_glob_59 from "../content/docs/dashboard/posts/drafts.md?collection=docs"
import * as __fd_glob_58 from "../content/docs/dashboard/posts/[id].md?collection=docs"
import * as __fd_glob_57 from "../content/docs/dashboard/bulk-tools/video.md?collection=docs"
import * as __fd_glob_56 from "../content/docs/dashboard/bulk-tools/image.md?collection=docs"
import * as __fd_glob_55 from "../content/docs/post-types/video.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/post-types/thread.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/post-types/text.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/post-types/index.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/post-types/image.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/post-types/collection.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/features/scheduling.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/features/queue.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/features/index.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/features/bulk-tools.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/features/auto-repost.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/developer/index.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/developer/architecture.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/platforms/youtube.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/platforms/twitter.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/platforms/tiktok.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/platforms/threads.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/platforms/pinterest.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/platforms/linkedin.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/platforms/instagram.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/platforms/index.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/platforms/facebook.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/platforms/bluesky.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/onboarding/step4.md?collection=docs"
import * as __fd_glob_31 from "../content/docs/onboarding/step3.md?collection=docs"
import * as __fd_glob_30 from "../content/docs/onboarding/step2.md?collection=docs"
import * as __fd_glob_29 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/getting-started/connecting-accounts.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/dashboard/teams.md?collection=docs"
import * as __fd_glob_26 from "../content/docs/dashboard/settings.md?collection=docs"
import * as __fd_glob_25 from "../content/docs/dashboard/queue.md?collection=docs"
import * as __fd_glob_24 from "../content/docs/dashboard/posts.md?collection=docs"
import * as __fd_glob_23 from "../content/docs/dashboard/more.md?collection=docs"
import * as __fd_glob_22 from "../content/docs/dashboard/feedback.md?collection=docs"
import * as __fd_glob_21 from "../content/docs/dashboard/create.md?collection=docs"
import * as __fd_glob_20 from "../content/docs/dashboard/create-type.md?collection=docs"
import * as __fd_glob_19 from "../content/docs/dashboard/connections.md?collection=docs"
import * as __fd_glob_18 from "../content/docs/dashboard/composer.md?collection=docs"
import * as __fd_glob_17 from "../content/docs/dashboard/calendar.md?collection=docs"
import * as __fd_glob_16 from "../content/docs/dashboard/bulk-tools.md?collection=docs"
import * as __fd_glob_15 from "../content/docs/dashboard/billing.md?collection=docs"
import * as __fd_glob_14 from "../content/docs/dashboard/api-keys.md?collection=docs"
import * as __fd_glob_13 from "../content/docs/billing/plans.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/billing/index.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/billing/faq.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/auth/verify-email.md?collection=docs"
import * as __fd_glob_9 from "../content/docs/auth/reset-password.md?collection=docs"
import * as __fd_glob_8 from "../content/docs/auth/forgot-password.md?collection=docs"
import * as __fd_glob_7 from "../content/docs/terms.md?collection=docs"
import * as __fd_glob_6 from "../content/docs/privacy.md?collection=docs"
import * as __fd_glob_5 from "../content/docs/onboarding.md?collection=docs"
import * as __fd_glob_4 from "../content/docs/index.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/index.md?collection=docs"
import * as __fd_glob_2 from "../content/docs/dashboard.md?collection=docs"
import * as __fd_glob_1 from "../content/docs/auth.md?collection=docs"
import * as __fd_glob_0 from "../content/docs/README.md?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {}, {"README.md": __fd_glob_0, "auth.md": __fd_glob_1, "dashboard.md": __fd_glob_2, "index.md": __fd_glob_3, "index.mdx": __fd_glob_4, "onboarding.md": __fd_glob_5, "privacy.md": __fd_glob_6, "terms.md": __fd_glob_7, "auth/forgot-password.md": __fd_glob_8, "auth/reset-password.md": __fd_glob_9, "auth/verify-email.md": __fd_glob_10, "billing/faq.mdx": __fd_glob_11, "billing/index.mdx": __fd_glob_12, "billing/plans.mdx": __fd_glob_13, "dashboard/api-keys.md": __fd_glob_14, "dashboard/billing.md": __fd_glob_15, "dashboard/bulk-tools.md": __fd_glob_16, "dashboard/calendar.md": __fd_glob_17, "dashboard/composer.md": __fd_glob_18, "dashboard/connections.md": __fd_glob_19, "dashboard/create-type.md": __fd_glob_20, "dashboard/create.md": __fd_glob_21, "dashboard/feedback.md": __fd_glob_22, "dashboard/more.md": __fd_glob_23, "dashboard/posts.md": __fd_glob_24, "dashboard/queue.md": __fd_glob_25, "dashboard/settings.md": __fd_glob_26, "dashboard/teams.md": __fd_glob_27, "getting-started/connecting-accounts.mdx": __fd_glob_28, "getting-started/index.mdx": __fd_glob_29, "onboarding/step2.md": __fd_glob_30, "onboarding/step3.md": __fd_glob_31, "onboarding/step4.md": __fd_glob_32, "platforms/bluesky.mdx": __fd_glob_33, "platforms/facebook.mdx": __fd_glob_34, "platforms/index.mdx": __fd_glob_35, "platforms/instagram.mdx": __fd_glob_36, "platforms/linkedin.mdx": __fd_glob_37, "platforms/pinterest.mdx": __fd_glob_38, "platforms/threads.mdx": __fd_glob_39, "platforms/tiktok.mdx": __fd_glob_40, "platforms/twitter.mdx": __fd_glob_41, "platforms/youtube.mdx": __fd_glob_42, "developer/architecture.mdx": __fd_glob_43, "developer/index.mdx": __fd_glob_44, "features/auto-repost.mdx": __fd_glob_45, "features/bulk-tools.mdx": __fd_glob_46, "features/index.mdx": __fd_glob_47, "features/queue.mdx": __fd_glob_48, "features/scheduling.mdx": __fd_glob_49, "post-types/collection.mdx": __fd_glob_50, "post-types/image.mdx": __fd_glob_51, "post-types/index.mdx": __fd_glob_52, "post-types/text.mdx": __fd_glob_53, "post-types/thread.mdx": __fd_glob_54, "post-types/video.mdx": __fd_glob_55, "dashboard/bulk-tools/image.md": __fd_glob_56, "dashboard/bulk-tools/video.md": __fd_glob_57, "dashboard/posts/[id].md": __fd_glob_58, "dashboard/posts/drafts.md": __fd_glob_59, "dashboard/posts/posted.md": __fd_glob_60, "dashboard/posts/scheduled.md": __fd_glob_61, "developer/pages/index.mdx": __fd_glob_62, "developer/pages/posts.mdx": __fd_glob_63, "dashboard/connect/instagram-facebook/select.md": __fd_glob_64, "dashboard/connections/facebook/select.md": __fd_glob_65, "dashboard/posts/[id]/edit.md": __fd_glob_66, "dashboard/connections/instagram/select.md": __fd_glob_67, "dashboard/connections/linkedin/select.md": __fd_glob_68, });